### ISSUE TITLE
Shell script will not read parameters passed

### ISSUE THREAD

**Issue by georgp24** [ghaerr/elks#103] opened 2017-03-25 10:00 UTC
The following one line script will not echo the parameter passed:
`echo $1 `

So if you run this script line with e.g. `test.sh 123` it will not echo `123`

You cannot use $1 with other commands as well.

**Comment by mfld-fr** [comment] 2017-11-10 08:02
While compiling with GCC-IA16, saw a big warning about arguments in execve. Have to look deeper at that, because it seems related to this issue.

**Comment by mfld-fr** [comment] 2018-04-17 20:37
Just tested it on `full3` image as root under QEMU with default configuration:
```
echo echo `$*` > test.sh
./test.sh a b c
```
Result is:
```
a b c
```
So it works well with the `ash` shell that is linked from `sh` in that configuration.
I also tested with the `sash` shell, that works well either.
Therefore closing this issue as non-reproducible.

**Closed as completed** 2018-04-17 20:54 UTC
Labels: unconfirmed
